var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
var strArr1;
var numArr1;
var boolArr1;
var strNumTuple;
myString = 'Hello World';
myNum = 0xf00d;
strArr = ['Hello', 'World'];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myVoid);
